version: "3.9"
services:
  acme-product-query:
    image: rabbitmq:3.11.10-management-alpine
    container_name: 'rabbitmq-query'
    restart: always
    ports:
      - 5673:5673
      - 15672:15672
    volumes:
      - ./dados:/var/lib/rabbitmq/
    environment:
      - "RABBITMQ_DEFAULT_USER=admin"
      - "RABBITMQ_DEFAULT_PASS=123456"