"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var express_1 = require("express");
var productController_1 = require("../api/controller/productController");
var routes = (0, express_1.Router)();
routes.get("/products", productController_1.default.findAllProducts);
routes.get("/products/sku/:sku", productController_1.default.findProductBySku);
routes.get("/products/id/:id", productController_1.default.findProductById);
routes.get("/products/designation/:designation", productController_1.default.searchByDesignation);
routes.post("/products", productController_1.default.create);
routes.delete('/products/:sku', productController_1.default.deleteBySku);
routes.delete('/products/:sku', productController_1.default.updateProduct);
exports.default = routes;
